### ISSUE TITLE
sql questor

### ISSUE THREAD

**Issue by cornebistouille** [google/alligator2#1]
hello, 
i have done a python file to automatically generate SQL table needed to be used in the datastudio sample that you provided (i am new to notebook usage and more confident with directly writting scripts (yes i am a boomer)  
as i am quite new with python, it has been quite hard for me to understand that after the main.py, i had to ingest queries that were in sql directory to use it in the sample... 
may be that could help 
i agreed with Google participation policies, but can't for now upload anything so i put it there...
and thanks for this very usefull work :)
[sql_questor.py.txt](https://github.com/google/alligator2/files/5433351/sql_questor.py.txt)

**Comment by tonycoco** [comment]
Ahh, I see what you're trying to do. The current codease does not automatically upload the SQL sample queries to BigQuery for analysis. I will look into adding something to our `main.py` process that will capture what you have requested. Thanks for sharing!
