### ISSUE TITLE
Incomplete import on multi-accounts set-up

### ISSUE THREAD

**Issue by Chassaga** [google/alligator2#2]
Hello,

I have a multi-account set-up on my Google My Business and I need to extract insights and reviews to analyse them on BigQuery.
I have mounted the alligator2 repo on a VM with Compute Engine. 
Nevertheless my last import, which was completed without errors gave out uncompleted results.

As a patch, we tried to download the data on an account by account basis, which lead to incomplete results as well.

What is the most surprising is that on previous import, the account by account way was functionnal.
Thank you for that repository which is of great help.

**Comment by tonycoco** [comment]
How were the results incomplete? Were you missing accounts or reviews?

**Comment by cornebistouille** [comment]
Hello i had a lot of errors with GMB Api who seems to be not very happy when yours reviews are too many (above 5000) and started to send 500 error... to avoid that, i modified reviews() fonction in api.py by catching the error and go to the next location.
its a quick fix (a ticket has been sublitted to GMB api) but at least, i can manage to get all y 550 locations over 4 directions...
`
  def reviews(self, location_id):
    page_token = None

    while True:
      try : response_json = self.gmb_service.accounts().locations().reviews().list(
          parent=location_id,
          pageToken=page_token).execute(num_retries=MAX_RETRIES)
      except HttpError : 
        logging.error("============= "+location_id+" has a too big list ==========")
        break #go to next location        
      try : data = response_json.get("reviews") or []
      except HttpError : 
        logging.error("============= "+location_id+" has too much reviews ==========")
        break #go to next location
 
      logging.debug(json.dumps(data, indent=2))
      self.to_bigquery(table_name="reviews", data=data)
      page_token = response_json.get("nextPageToken")
      if not page_token:
        break
`
I still don't know how to propose my api.py version in github (yes, i know) but if the devellopers want to put it in ther code, no soucy 👍

**Comment by Chassaga** [comment]
Hello,
The problem was due to the expiration of the session of the Cloud shell, set to 20 minutes.
For the same reason when running from Compute Engine, the import wasn't complete.
But when run with a closer attention, the import was successful.
Thanks a lot.
