### ISSUE TITLE
Getting Authorization Error on browser

### ISSUE THREAD

**Issue by jigyasu11** [google/alligator2#6]
When I run project with specified command:   `python main.py --project_id='my-proj-id'`

It spits out a url to paste to in browser for authentication. When I paste the URL on browser, I get following error:
```
Error 400: redirect_uri_mismatch
The redirect URI in the request, urn:ietf:wg:oauth:2.0:oob, can only be used by a Client ID for native application. It is not allowed for the WEB client type. You can create a Client ID for native application at https://console.developers.google.com/apis/credentials/oauthclient
```

I generated the oAuth credentials for web application. Can you please tell what do I need to setup to make this code work?

**Comment by mohabfekry** [comment]
Please generate the OAuth Credentials for a "Desktop app" instead. Refer to this [Support page](https://support.google.com/cloud/answer/6158849?hl=en#zippy=%2Cnative-applications) for more information.
